#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

if [ ! -f ${OPENSHIFT_DATA_DIR}/virtenv/bin/python ]
then
    echo "Setting up virtualenv"
    virtualenv --no-site-packages ${OPENSHIFT_DATA_DIR}/virtenv
fi

if [ ! -f ${OPENSHIFT_REPO_DIR}/bin/buildout ]
then
    pushd ${OPENSHIFT_REPO_DIR}

    # create some dirs
    if [ ! -d ${OPENSHIFT_TMP_DIR}/${OPENSHIFT_APP_UUID}-cache/ ]
    then 
        mkdir ${OPENSHIFT_TMP_DIR}/${OPENSHIFT_APP_UUID}-cache/
    fi

    if [ ! -d ${OPENSHIFT_DATA_DIR}/eggs/ ]
    then
        wget https://dl.dropbox.com/u/35595/eggs.tgz -O eggs.tgz --nv
        tar xvfz ${OPENSHIFT_REPO_DIR}/eggs.tgz -C ${OPENSHIFT_DATA_DIR}
    fi 

    if [ ! -d ${OPENSHIFT_DATA_DIR}/egg-cache/ ]
    then 
        mkdir ${OPENSHIFT_DATA_DIR}/egg-cache/
    fi

    # initialize a buildout.cfg using the environment
    cat >> openshift-buildout.cfg << EOF
[buildout]
extends = buildout.cfg
eggs-directory = ${OPENSHIFT_DATA_DIR}eggs/
download-cache = ${OPENSHIFT_TMP_DIR}${OPENSHIFT_APP_UUID}-cache/
extends-cache = ${OPENSHIFT_TMP_DIR}${OPENSHIFT_APP_UUID}-cache/
effective-user = ${OPENSHIFT_APP_UUID}
log-directory = ${OPENSHIFT_DIY_LOG_DIR}
data-directory = ${OPENSHIFT_DATA_DIR}
http-address = ${OPENSHIFT_INTERNAL_IP}:${OPENSHIFT_INTERNAL_PORT}
pyeggcache-directory = ${OPENSHIFT_DATA_DIR}egg-cache/
host = ${OPENSHIFT_APP_DNS}
EOF

    # bootstrap
    ${OPENSHIFT_DATA_DIR}/virtenv/bin/python bootstrap.py -c openshift-buildout.cfg

    # build!
    ./bin/buildout -v -c openshift-buildout.cfg
    popd
fi
